### ISSUE TITLE
Table header beginning with named anchor results in `panic()`

### ISSUE THREAD

**Issue by JordanMilne** [kivikakk/comrak#34]
Minimal repro with `table` extension enabled:

```
[a
]: a
-|-:
```

A table following a named anchor on a single line, however, does *not* cause a `panic()`:

```
[a]: a
-|-:
```

Backtrace:

```
$ RUST_BACKTRACE=1 ./target/debug/comrak --to html --extension table table-crash.md 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:32
  11: comrak::parser::Parser::add_text_to_container
             at src/parser/mod.rs:850
  12: comrak::parser::Parser::process_line
             at src/parser/mod.rs:351
  13: comrak::parser::Parser::feed
             at src/parser/mod.rs:265
  14: comrak::parser::parse_document
             at src/parser/mod.rs:43
  15: comrak::main
             at src/main.rs:139
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  18: main
  19: __libc_start_main
  20: <unknown>
```

As far as I can tell, this is because we end up with a `NodeValue::Table` that has no parent, and panics during the `.unwrap()` when `node.parent()` is returned from `Parser::finalize_borrowed`.

**Comment by JordanMilne** [comment]
Looks like this is a more general issue with things that look like references anchors on lines that look like table headers. This also repros:

```
[a]:|a|a
-|-|-
```

**Comment by kivikakk** [comment]
Trying to work out how we end up with a table with no parent; at the same place in `cmark-gfm`, the table does have a parent and it terminates successfully.

**Comment by kivikakk** [comment]
Subtle bug: I was using `parser.add_child` in the table extension and then swapping the node out, whereas in the C version we simply overwrite the node in place. `parser.add_child` caused finalisation where it shouldn't have happened.
